neodymium.ai.generate = true
#neodymium.url = https://www.google.com/
#neodymium.url.includeList = ^https?://www.google.com

neodymium.workInProgress = true

neodymium.ai.generate.v2 = true

neodymium.ai.generate.v2.diagnosticLogs = true

neodymium.allureAddons.screenshots.perstep.always = true

#neodymium.debugUtils.highlight.duration = 100

neodymium.ai.interactive = false