package com.xceptance.neodymium.ai.test.videoRecording;

import com.xceptance.neodymium.common.browser.Browser;
import com.xceptance.neodymium.common.testdata.DataFolder;
import com.xceptance.neodymium.junit5.NeodymiumTest;
import com.xceptance.neodymium.util.Neodymium;

/**
 * Runner mapped to the "fromvideo" DataFolder.
 * 
 * Replays any AI-generated test playbooks that were extracted from manual video recording sessions
 * (typically generated by {@link RecordVideoTestPOC}).
 */
@Browser
@DataFolder("videoRecordings")
public class ExecuteRecordedVideoTest {

    @NeodymiumTest
    void executePlaybook() throws Throwable
    {
        // Executes the Neodymium automated test driver against the prompt 
        // compiled by Gemini during the video extraction phase.
        Neodymium.ai().execute();
    }
}
