services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: posters-demo-store:latest
    container_name: posters-demo-store
    ports:
      - "8080:8080"
      - "7091:7091"
    volumes:
      - ./db:/app/db
      - ./log:/app/log
    restart: unless-stopped
