name: Build
on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source files
        uses: actions/checkout@v2

      - name: Set up JDK 11 and Maven repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-passphrase: GPG_PASSPHRASE

      - name: Prepare the Maven repo cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2    

      - name: Compile, test, and package the project with Maven
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.GPG_KEY }}" | gpg --batch --import
          mvn -B deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Compile, test, package, and deploy the project with Maven
        if: github.event_name == 'release'
        run: |
          echo "${{ secrets.GPG_KEY }}" | gpg --batch --import
          mvn -B deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Add build artifacts to staging area
        run: |
          mkdir staging
          cp target/*.[jw]ar staging

      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: BuildArtifacts
          path: staging