name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source files
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Prepare the Maven repo cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2    

      - name: Copy customized settings.xml
        run: cp .github/workflows/settings.xml ~/.m2

      - name: Run the build with Maven
        run: mvn -B verify
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Log in to Docker Hub
        run: echo -n $DOCKERHUB_PASSWORD | docker login --username xceptance --password-stdin
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Add artifacts to staging area
#        run: mkdir staging && cp target/*.war staging

#      - name: Upload artifacts
#        uses: actions/upload-artifact@v1
#        with:
#          name: MyArtifact
#          path: staging